/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package first.game;
import java.awt.*;

public class Game extends Canvas implements Runnable {
    public static final int WIDTH = 1920, HEIGHT = WIDTH / 12 * 9;

    public Game(){
        new Window(WIDTH,HEIGHT,"Let's Build a Game!", this);
    }

    public synchronized void start(){

    }
    public void run(){

    }

    public static void main(String[] args) {
        new Game();
    }
}
